### ISSUE TITLE
About the results in main table 

### ISSUE THREAD

**Issue by kunmel** [YuWVandy/KG-LLM-MDQA#11]
Hi,
While going through the paper, I'm a little confused about the results in the main table (table 1). Could you please point out why does the golden Acc only reach 57.00 in MuSique and 62.68 in IIRC, since you have provided the golden context for LLM.

**Comment by YuWVandy** [comment]
> Hi, While going through the paper, I'm a little confused about the results in the main table (table 1). Could you please point out why does the golden Acc only reach 57.00 in MuSique and 62.68 in IIRC, since you have provided the golden context for LLM.

Thank you for your interest!

There are two reasons:
(1) At that moment, we indeed interacted with ChatGPT a lot and we found for many complex questions, the capability of ChatGPT to answer it correctly is not that accurate compared to the current version.
(2) IIRC and MuSiQue are far more complex involving a lot of questions  (if you check the questions in IIRC, there are a lot of questions asking "how many/how long", which requires math calculation) requiring deep understanding and comprehension, here is one example that even using the current ChatGPT, it can still not answer correctly:

=======Ex1=======
How many years did the event last during which Wingfield lost much of his fortune?
Groundtruth Answer provided in the dataset: 9
Context 1: Much of Wingfield's fortune was lost during the Great Depression.
Context 2: The timing of the Great Depression varied across nations; in most countries, it started in 1929 and lasted until the late 1930s.

This one is because the difficulty when understanding 1930s
================

=======Ex2=======
How old was Greville's father when he died?
Groundtruth Answer in provided in the dataset: 53
Context 1: The son of Francis Greville, 1st Earl of Warwick,
Context 2: Francis Greville, 1st Earl of Warwick, KT (10 October 1719 \u2013 8 July 1773)

Although 1773 - 1719 = 54, since July is not later than October, so should be 53.
================

However, when I played with ChatGPT today, I indeed found that its ability to answer IIRC and MuSiQue becomes better than last summer when I worked on the paper, so it is expected to achieve higher performance on these two datasets. 

I really appreciate this question and please let me know if you have any follow-up question. Thank you!

**Comment by kunmel** [comment]
Thanks for the reply! I will try it with new version of ChatGPT.
